version: '3.7' 

services: 
    nginx: 
        image: nginx:1.15
        depends_on: 
            - php
            - mysql
        ports: 
            - "80:80"
        volumes: 
            - ./www:/var/www
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/sites:/etc/nginx/sites-available
            - ./config/nginx/sites:/etc/nginx/sites-enabled
        links: 
            - php
    php: 
        build: ./config/php/
        depends_on: 
            - memcached
            - redis
            - mongo
            - elasticsearch
        ports: 
            - "9000:9000"
        volumes: 
            - ./www:/var/www
            - ./config/php/conf:/etc/php/7.3
        links: 
            - mysql
            - memcached
            - mongo
            - redis
            - elasticsearch
    mysql: 
        image: percona:ps-8  
        ports: 
            - "3306:3306"
        volumes: 
            - /opt/mysql/data:/var/lib/mysql
            - /opt/mysql/dump:/docker-entrypoint-initdb.d
            - ./config/mysql/auth.cnf:/etc/my.cnf.d/auth.cnf
            - ./config/mysql/tuning.cnf:/etc/my.cnf.d/tuning.cnf
        environment: 
            MYSQL_USER: $MYSQLUSER
            MYSQL_PASSWORD: $MYSQLPASSWORD
            MYSQL_DATABASE: sibcastrol
            MYSQL_ROOT_PASSWORD: $MYSQLROOTPASSWORD
    memcached:
        image: memcached
        ports:
            - "11211:11211"
    mongo:
        image: mongo
        ports:
            - "27017:27017"
    redis:
        image: redis
        ports:
            - "6379:6379"
    elasticsearch:
        image: elasticsearch:6.6.1
        ports:
            - "9200:9200"
            - "9300:9300"
    pma: 
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on: 
            - mysql
        ports: 
            - "8138:80"
        links: 
            - mysql:mysql
        environment: 
            PMA_ABSOLUTE_URI: https://deltapma.sibcastrol.ru
            PMA_HOST: mysql
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: $MYSQLROOTPASSWORD
